name: Create Release & Deploy To Dev

on:
    push:
        branches:
            - "main"
        tags-ignore:
            - '**'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write
            
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Get short sha
              id: sha
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Create release
              env:
                GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                tag: ${{ steps.sha.outputs.sha_short }}
              run: |
                gh release create "pre-${tag}" \
                  --repo="$GITHUB_REPOSITORY" \
                  --title="pre-${tag}" \
                  --prerelease \
                  --generate-notes

            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.ACCESS_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: |
                    type=sha


            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
              with:
                context: src/
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
