name: Development Deploy 

concurrency: 
    group: development
    cancel-in-progress: true

on:
    push:
        branches:
        - main

permissions:
    contents: write

jobs:
    release:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Set short git commit SHA
            run: |
              calculatedSha=$(git rev-parse --short ${{ github.sha }})
              echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
          - name: Deploy To Development
            run: |
              echo "Build and upload container (${{ env.COMMIT_SHORT_SHA }})"
