name: Production Deploy 

on:
    release:
        types: [published]

permissions:
    contents: write

jobs:
    push:

        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - uses: actions/checkout@v4

            - name: Build image
              run: docker build . --file src/Dockerfile --tag release-flow:v${{ github.ref_name }}

            - name: Log in to registry
              run: echo "${{ secrets.ACCESS }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Publish container
              run: docker push ghcr.io/baggerspion/release-flow:v${{ github.ref_name }}