name: Development Deploy 

concurrency: 
    group: development
    cancel-in-progress: true

on:
    push:
        branches:
        - main

permissions:
    contents: write

jobs:
    release:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Deploy To Development
              env:
                tag: ${{ github.ref_name }}
              run: |
                echo "Build and upload container ($tag)"
