name: Create release

on:
    push:
        tags:
        - "v*"

permissions:
    contents: write

jobs:
    release:
        name: Release
        runs-on: ubuntu-22.04
        steps:
            - name: Create Release
              env:
                GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                tag: ${{ github.ref_name }}
              run: |
                gh release create "$tag" \
                  --repo="$GITHUB_REPOSITORY" \
                  --title="${tag#v}" \
                  --generate-notes
